### ISSUE TITLE
Next and Previous media keys unresponsive on keyboard and Touch Bar (M1 MacBook Pro)

### ISSUE THREAD

**Issue by timotealion** [steve228uk/YouTube-Music#119] opened 2021-03-06 01:55 UTC
Play/Pause works with focus and no focus.
Command -> and Command <- works with focus

**Comment by eaigner** [comment] 2021-03-22 19:47
Same issue, M1 Mac mini.

**Comment by Tolmark12** [comment] 2021-03-25 18:27
Any thoughts on how to fix this?

**Comment by justAsascha** [comment] 2021-03-29 07:52
Same on MBP 16" (intel)

**Comment by berkantaras** [comment] 2021-03-30 02:43
I am looking forward to having this problem resolved (M1 Air)

**Comment by dantnad** [comment] 2021-03-30 15:38
Same, Intel 13" MBP 2019

**Comment by harryfear** [comment] 2021-04-10 13:42
Same on 16" MBP

**Comment by yj990315** [comment] 2021-04-11 07:43
same MacBook m1 air

**Comment by ivogonzalvez** [comment] 2021-04-15 15:54
Same here 15" MBP (Mac OS Catalina)

**Comment by timotealion** [comment] 2021-04-16 17:14
Based on all the different configurations of Macs reported here, did it ever work?

**Comment by TimOliver** [comment] 2021-05-02 16:53
This is a duplicate of #33 so I'm going to close this issue in favour of continuing the discussion there. Thanks! :)

**Closed by TimOliver** 2021-05-02 16:53 UTC
