### ISSUE TITLE
Application does not load upon starting

### ISSUE THREAD

**Issue by marissarousseau** [steve228uk/YouTube-Music#129] opened 2021-04-25 15:45 UTC
I just updated to the latest version of the app (v1.1.0) and when I open the application, it doesn't load. Instead, it stays completely blank like so: 

![Screen Shot 2021-04-25 at 11 42 23 AM](https://user-images.githubusercontent.com/54009117/115999852-7f693200-a5bb-11eb-908d-c76dbdd77644.png)

I am running the application on macOS Big Sur 11.2.3. I have tried a completely fresh install and the same problem occurs.

**Comment by chew-z** [comment] 2021-04-25 19:52
Same

**Comment by TimOliver** [comment] 2021-04-26 00:08
Hmm. Sorry to see that folks. I’m not on Big Sur yet as I’m waiting for the 11.3 public release to drop. 

If anyone else can diagnose this, that would help a lot.

**Comment by johannsteenkamp** [comment] 2021-04-26 03:55
Me the same.
When starting from CLI can see the below error:
`2021-04-26 13:49:31.352 YT Music[58938:525721] *** Assertion failure in -[MPRemoteCommand addTarget:action:], MPRemoteCommand.m:135
2021-04-26 13:49:31.352 YT Music[58938:525721] Failed to set (contentViewController) user defined inspected property on (YT_Music.CustomWindow): Unsupported action method signature. Must return MPRemoteCommandHandlerStatus or take a completion handler as the second argument.
Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type}`

**Comment by TimOliver** [comment] 2021-04-26 16:09
@johannsteenkamp Thanks a lot for the report! That pointed me in the right direction.

Turns out [the problem is this block of code](https://github.com/steve228uk/YouTube-Music/blob/9fa97e07b2624a136855312f6274fadcf144ca1e/YT%20Music/Controllers/ViewController%20%2B%20MediaKeys.swift#L210). Those functions are supposed to be returning a 'succeeded' or 'failed' state value, and in older versions of macOS, not returning a value seemed to work just fine.

I tried commenting them out, and the app started working properly on Big Sur.

I'll have to work out the best way to support this. The code is written that way so it can gracefully fall back on macOS versions lower than macOS 10.12.2. Additionally, I might need to test this more, but the JavaScript execution code in there also seemed like it was hanging to me.

At this point, it might be easier to just bump the minimum version of the app up to macOS 10.13. But I'm not sure how many people might still want support for it at 10.11 still.

Sorry for the delay! I'll try and have a fixed version done ASAP.

**Comment by Photostation** [comment] 2021-04-26 18:26
Thank you for your great effort in helping us with this application
I have the same problem and we are waiting for you to solve it and we trust your talent

**Comment by albertbronsky** [comment] 2021-04-27 10:29
I have the same problem (blank window on start). I am on macOS Big Sur 11.3.

This is what it says in my system.log:
```
Apr 27 12:24:38 Alberts-MacBook-Air YT Music[1500]: getattrlist failed for /System/Library/Extensions/AppleIntelICLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelICLGraphicsGLDriver: #2: No such file or directory
Apr 27 12:24:38 Alberts-MacBook-Air YT Music[1500]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
```

**Comment by TimOliver** [comment] 2021-04-27 14:01
Alrighty folks! I just released version 1.1.1. HOPEFULLY this has now fixed the Big Sur issue.

Please give it a shot (You should be able to download it by choosing "Check for Updates") and let me know. :)

**Comment by marissarousseau** [comment] 2021-04-27 14:26
Looks like it's working! Thank you for working so quickly to fix it. Will close this issue now.

**Closed** 2021-04-27 14:26 UTC
Labels: bug, help wanted

**Comment by TimOliver** [comment] 2021-04-27 14:33
Woohoo! Awesome! Thanks so much @marissarousseau! Enjoy! :D

**Comment by akinnee** [comment] 2021-04-29 16:58
I was getting a blank screen in 1.1.1 on Catalina... and then as I switched to take a screenshot to comment here, it eventually loaded.
